apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: iotpilot
    jsonData:
      version: Flux
      organization: iotpilot
      defaultBucket: devices
    secureJsonData:
      token: my-super-secret-auth-token-for-local-testing

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
