# Traefik v3.0 configuration with SSL
api:
  dashboard: true
  debug: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: iotpilot-network
  file:
    directory: /etc/traefik/dynamic
    watch: true

# TLS certificates configuration
tls:
  certificates:
    - certFile: "/etc/traefik/certs/iotpilotserver.test.crt"
      keyFile: "/etc/traefik/certs/iotpilotserver.test.key"

log:
  level: DEBUG

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json

ping: {}

# Global middleware for local development
http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true