# Traefik v3.0 configuration with SSL for local development
api:
  dashboard: true
  debug: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    # NO automatic HTTPS redirect for local development

  websecure:
    address: ":443"
    http:
      tls:
        options: default

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: iotpilot-network
  file:
    directory: /etc/traefik/dynamic
    watch: true

# TLS certificates configuration for local development
tls:
  certificates:
    - certFile: "/etc/traefik/certs/iotpilotserver.test.crt"
      keyFile: "/etc/traefik/certs/iotpilotserver.test.key"

log:
  level: DEBUG

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json

ping: {}

# HTTP middleware for local development (no redirects)
http:
  middlewares:
    compression:
      compress: {}

    security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: false  # Allow frames for local development
        customFrameOptionsValue: "SAMEORIGIN"
        # NO SSL redirect for local development