http:
  routers:
    api:
      rule: "Host(`${DOMAIN}`) && PathPrefix(`/traefik`)"
      service: api@internal
      middlewares:
        - auth
        - security-headers
      tls:
        certResolver: letsencrypt

    # Add InfluxDB routing
    influxdb:
      rule: "Host(`${DOMAIN}`) && PathPrefix(`/influxdb`)"
      service: influxdb
      middlewares:
        - auth
        - security-headers
        - influxdb-strip-prefix
      tls:
        certResolver: letsencrypt

    # Add Grafana routing
    grafana:
      rule: "Host(`${DOMAIN}`) && PathPrefix(`/grafana`)"
      service: grafana
      middlewares:
        - security-headers
        - grafana-strip-prefix
      tls:
        certResolver: letsencrypt

  services:
    influxdb:
      loadBalancer:
        servers:
          - url: "http://influxdb:8086"

    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"

  middlewares:
    influxdb-strip-prefix:
      stripPrefix:
        prefixes:
          - "/influxdb"

    grafana-strip-prefix:
      stripPrefix:
        prefixes:
          - "/grafana"

tcp:
  routers:
    mqtt:
      rule: "HostSNI(`*`)"
      service: mqtt
      entryPoints:
        - mqtt

  services:
    mqtt:
      loadBalancer:
        servers:
          - address: "mosquitto:1883"